### ISSUE TITLE
Prefixar a data no nome do arquivo

### ISSUE THREAD

**Issue by ednilson** [scieloorg/onix#10]
O xml gerado deverá ser prefixado com a data atual no formato YYYYMMDD.

**Comment by ednilson** [comment]
Poderá ser configurado em config.ini

**Comment by amandasramalho** [comment]
@ednilson 
Ou seja, precisamos colocar a data manualmente?

**Comment by ednilson** [comment]
Não. Será automático.
No arquivo de configuração você poderá ajustar quando irá usar somente a data, somente um nome ou ambos.
A data é automática.
