### ISSUE TITLE
Verificar encoding ao produzir o XML no Windows

### ISSUE THREAD

**Issue by ednilson** [scieloorg/onix#12]

**Comment by ednilson** [comment]
@amandasramalho por favor baixe o .zip e teste o executável. Veja se o não há problemas com encoding ao submeter o XML.

**Comment by amandasramalho** [comment]
@ednilson Enviei um modelo de registros para a EBSCO Discovery Service e foi validado com sucesso! Então está tudo certo com o encoding.

**Comment by ednilson** [comment]
@amandasramalho envie-me o XML que foi enviado para a EditEUR.

**Comment by amandasramalho** [comment]
@ednilson Como conversamos, enviei um modelo de ONIX para avaliação da EDItEUR e o retorno referente a codificação do arquivo foi:

> Your file says on the first line encoding=“UTF-8” – but in fact the file is NOT UTF-8. It is actually (so far as I can tell) in the Windows-1252 character set. This means you have to have encoding=“Windows-1252” at the top of the file.

O arquivo enviado foi: 
[20171127_EDUEPB.zip](https://github.com/scieloorg/onix/files/1518942/20171127_EDUEPB.zip)

**Comment by ednilson** [comment]
@amandasramalho veja:
```
Teste do arquivo gerado no Windows:
$ file 20171127_EDUEPB.xml
20171127_EDUEPB.xml: XML 1.0 document, Non-ISO extended-ASCII text, with very long lines, with CRLF line terminators

Teste do arquivo gerado no Linux:
$ file teste.xml
teste.xml: XML 1.0 document, UTF-8 Unicode text, with very long lines```

Então preciso analisar como é gerado no Windows.

**Comment by amandasramalho** [comment]
Agora parece que corrigiu o encoding! Os acentos estão sendo interpretados pelo Notepad++ e no rodapé aponta como "UTF-8 BOM".

**Comment by ednilson** [comment]
q BOM
