### ISSUE TITLE
Incluir tag <EpubLicense>

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/onix#20]
Antes da tag `<TitleDetail>`, incluir:
```
<EpubLicense>
     <EpubLicenseName>Creative Commons License</EpubLicenseName> <!-- Informação fixa -->
     <EpubLicenseExpression>
          <EpubLicenseExpressionType>02</EpubLicenseExpressionType><!-- Informação fixa -->
          <EpubLicenseExpressionLink>https://creativecommons.org/licenses/by-nc/4.0/</EpubLicenseExpressionLink> <!-- Puxar informação do campo Use Licence -->
     </EpubLicenseExpression>
</EpubLicense>
```

**Comment by amandasramalho** [comment]
A tag de `<EpubLicense>` acabou ficando dentro de `<Collection>`. Não lembrei que em Collection também havia um `<TitleDetail>`. O bloco `<EpubLicense>` deve vir antes de `<Collection>` (depois de `<PrimaryContentType>`)

**Comment by ednilson** [comment]
Exemplo:

```
  <PrimaryContentType>10</PrimaryContentType>
  <EpubLicense>
    <EpubLicenseName>Creative Commons License</EpubLicenseName>
    <EpubLicenseExpression>
      <EpubLicenseExpressionType>02</EpubLicenseExpressionType>
      <EpubLicenseExpressionLink>https://creativecommons.org/licenses/by-nc/4.0/</EpubLicenseExpressionLink>
    </EpubLicenseExpression>
  </EpubLicense>
  <Collection>
    <CollectionType>10</CollectionType>
    <TitleDetail>
      <TitleType>01</TitleType>
      <TitleElement>
        <SequenceNumber>1</SequenceNumber>
        <TitleElementLevel>02</TitleElementLevel>
        <TitleText language="por">Antropologia e saúde</TitleText>
      </TitleElement>
    </TitleDetail>
  </Collection>
```

**Comment by ednilson** [comment]
@amandasramalho EpubLicense ficará dentro de <DescriptiveDetail>

**Comment by amandasramalho** [comment]
@ednilson Sim!

**Comment by ednilson** [comment]
@amandasramalho executável atualizado pronto para testes.
https://github.com/scieloorg/onix/blob/master/onix/dist/onix.zip

**Comment by amandasramalho** [comment]
Testado e agora a tag está Ok!

**Comment by amandasramalho** [comment]
@ednilson 
Edy, a tag tá sendo incluída mesmo quando o campo da licença está vazio no backoffice.
Se o livro é comercial, a tag <EpubLicense> inteira não deve ser incluída. (Podem ser usadas 2 regras: se o campo Use License estiver vazia, não incluir. Ou se o valor das moedas forem maiores que 0,01, não incluir.)

**Comment by ednilson** [comment]
Eu poderia analisar a tag 'is_comercial'?

**Comment by amandasramalho** [comment]
Ed,

Sim. Sempre que um livro for comercial, estará identificado nesta tag no
backoffice.

Att.,
--

*Amanda Ramalho*
SciELO Books Unit
FAPESP – CAPES – CNPq – BIREME– FapUNIFESP – ABEU
Programa SciELO/FAPESP
____________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639 Ramal 115
livros.scielo.org | www.scielo.br

2018-03-15 12:26 GMT-03:00 Ednilson Gesseff <notifications@github.com>:

**Comment by ednilson** [comment]
Então adotei essa regra:
Se is_comercial = False, inclui a tag </EpubLicense>.
Se is_comercial = True, não incluir.

**Comment by amandasramalho** [comment]
Tá perfeito.

**Comment by ednilson** [comment]
@amandasramalho  Por favor, baixar e realizar os testes no Windows.
https://github.com/scieloorg/scielobooks_exports/blob/master/onix/README.md
