### ISSUE TITLE
Incluir http:// em <ResourceLink> e <WebsiteLink>

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/onix#27]
As URLs destes campos estão iniciando somente com "books.scielo.org". A EDItEUR orientou que incluíssemos os http://. Precisamos somente observar que quando os sites mudarem para https://, isso deverá ser refletido no ONIX também.

**Comment by ednilson** [comment]
Isto já é configurável no arquivo config.ini no bloco [books.scielo], parametro host. Veja exemplo abaixo.
```
[books.scielo]
# Host of SciELO Books website [required]
host = http://books.scielo.org
```
