### ISSUE TITLE
 Incluir tag <UnpricedItemType> se o valor de <PriceAmount> for 0,00

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/onix#28]
A EDItEUR orientou que não incluíssemos o valor de 0,00 em `<PriceAmount>`. Sempre que o valor for 0, deverá ser incluída a tag `<UnpricedItemType>` no lugar do bloco inteiro de `<price>`.

Como está atualmente:
```
<Price>
          <PriceTypeCode>01</PriceTypeCode>
          <PriceAmount>0.00</PriceAmount>
          <CurrencyCode>USD</CurrencyCode>
          <Territory>
            <CountriesIncluded>AD AE AF AG AI AL AM AN AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CS CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET FI FJ FK FM FO FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UM US UY UZ VA VC VE VG VI VN VU WF WS YE YT YU ZA ZM ZW</CountriesIncluded>
          </Territory>
        </Price>
```

Mudar para:
`<UnpricedItemType>01</UnpricedItemType>`

**Comment by ednilson** [comment]
@amandasramalho  E se o valor for 0 para BRL e USD? Apresentar somente 1 vez a tag UnpricedItemType?
Ou se for 0 para um e não para outro?

**Comment by amandasramalho** [comment]
@ednilson Bem observado. 
**Regras:**
**BRL e USD for 0**= Sim, somente incluir 1x a tag UnpricedItemType. (Não pode haver tags `<price>` se esta tag estiver no código).
**se for 0 para um e não para outro**=  o que estiver com valor de 0,00, retirar a tag `<price>`. O outro que tiver valor, mudar o `<RegionsIncluded>` para o valor WORLD.
