### ISSUE TITLE
Nome completo da editora em <PublisherName>

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/onix#37]
A EDItEUR orientou que fosse incluído o nome completo da editora em `<PublisherName>`. Nós não temos esse campo no backoffice. É possível criar uma lista de equivalência no config.ini?

Editora FIOCRUZ - Editora da Fundação Oswaldo Cruz
EDUFBA - Editora da Universidade Federal da Bahia
Editora UNESP - Fundação Editora da UNESP
EDUEPB - Editora da Universidade Estadual da Paraíba
EDUEL - Editora da Universidade Estadual de Londrina
EdUFSCar - Editora da Universidade Federal de São Carlos
Editora Fap-Unifesp - Editora da Universidade Federal de São Paulo
EDUEM - Editora da Universidade Estadual de Maringá
Editora Mackenzie - Editora Mackenzie
EDUERJ - Editora da Universidade do Estado do Rio de Janeiro
Editora UEPG - Editora da Universidade Estadual de Ponta Grossa
Editus - Editora da Universidade Estadual de Santa Cruz
Editorial Universidad del Rosario - Editorial Universidad del Rosario
Editora da UFRGS - Editora da Universidade Federal do Rio Grande do Sul
Centro Edelstein - Centro Edelstein
JBRJ - Jardim Botânico do Rio de Janeiro
Sociedade Brasileira de Zoologia - Sociedade Brasileira de Zoologia
ReBentos - Rede de Monitoramento de Habitats Bentônicos Costeiros

**Comment by ednilson** [comment]
@amandasramalho será criado um arquivo "full_name_publishers.py" que acompanhará o pacote .zip. O conteúdo dele será estruturado em forma de dicionário {Key : Value} e poderá ser editado a qualquer momento.

**Comment by amandasramalho** [comment]
O arquivo "fullname.py" foi trocado por "publishers.json'. Funcionou corretamente!
